target-version = "py311"
builtins = [
    # Players:
    "Player",
    "Pa",
    "Pb",
    "Pc",
    "Pd",
    "Pe",
    "Pf",
    "Pg",
    "Ph",
    "Pi",
    "Pj",
    "Pk",
    "Pl",
    "Pm",
    "Pn",
    "Po",
    "Pp",
    "Pq",
    "Pr",
    "Ps",
    "Pt",
    "Pu",
    "Pv",
    "Pw",
    "Px",
    "Py",
    "Pz",
    "PA",
    "PB",
    "PD",
    "PE",
    "PF",
    "PG",
    "PH",
    "PI",
    "PJ",
    "PK",
    "PL",
    "PM",
    "PN",
    "PO",
    "PP",
    "PQ",
    "PR",
    "PS",
    "PT",
    "PU",
    "PV",
    "PW",
    "PX",
    "PY",
    "PZ",
    # sardine stuff
    "clock",   # access and change tempo, phase neat, bar
    "bowl",    # pause/resume/stop clock
    "silence", # gentle shutdown
    "panic",   # hard stop
    "swim",
    "solo",
    "die",
    "again",
    "sleep",
    "V",       # Amphibian variables
    # Sardine patterns senders
    "d",  # SuperDirt - samples and synthesizers (Player)
    "D",  # SuperDirt - samples and synthesizers (@swim)
    "n",  # MIDI notes (Player)
    "N",  # MIDI notes (@swim)
    "cc", # MIDI control messages (Player)
    "CC", # MIDI control messages (@swim)
    "pc", # MIDI program changes (Player)
    "PC", # MIDI program changes (@swim)
    "sy", # MIDI sysex message (Player)
    "SY", # MIDI sysex message (@swim)
    # Ziffers patterns senders
    "zd", # Ziffers SuperDirt - samples/synths with Ziffers patterns (Player)
    "ZD", # Ziffers SuperDirt - samples/synths with Ziffers patterns (@swim)
    "zn", # Ziffers MIDI notes with Ziffers patterns (Player)
    "ZN", # Ziffers MIDI notes with Ziffers patterns (@swim)
    "P",  # Pattern Object
    # Vortex (TidalCycles)
    "d1",
    "d2",
    "d3",
    "d4",
    "d5",
    "d6",
    "d7",
    "d8",
    "d9",
    "hush",
    "tidal",
    "s",
]
line-length = 100

[lint.per-file-ignores]
# Ignore F401 (imported but unused) in init files
"__init__.py" = ["F401"]
